#### StandardScaler

##### Standardizes numerical features to have:

##### Mean = 0

##### Standard Deviation = 1

In [1]:
from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([[20], [40], [60], [80], [100]])

scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

print(scaled_data)


[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


In [43]:
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Load the dataset
data = load_breast_cancer()
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target
print(df.shape)


X = df.drop('target', axis=1)
y = df['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


# Feature Scaling (Important for Logistic Regression)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(X_test_scaled)


(569, 31)
[[-0.46649743 -0.13728933 -0.44421138 ... -0.19435087  0.17275669
   0.20372995]
 [ 1.36536344  0.49866473  1.30551088 ...  0.99177862 -0.561211
  -1.00838949]
 [ 0.38006578  0.06921974  0.40410139 ...  0.57035018 -0.10783139
  -0.20629287]
 ...
 [-0.73547237 -0.99852603 -0.74138839 ... -0.27741059 -0.3820785
  -0.32408328]
 [ 0.02898271  2.0334026   0.0274851  ... -0.49027026 -1.60905688
  -0.33137507]
 [ 1.87216885  2.80077153  1.80354992 ...  0.7925579  -0.05868885
  -0.09467243]]


In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

# Sample DataFrame
df = pd.DataFrame({
    'Age': [25, 32, 47, 19, 55],
    'Income': [50000, 64000, 120000, 32000, 150000]
})

scaler = StandardScaler()

# Fit and transform
scaled_values = scaler.fit_transform(df)

# Create scaled DataFrame
scaled_df = pd.DataFrame(scaled_values, columns=df.columns)
print(scaled_df)


        Age    Income
0 -0.786936 -0.745783
1 -0.267261 -0.431296
2  0.846327  0.826651
3 -1.232371 -1.150123
4  1.440241  1.500552


##### MinMaxScaler

In [2]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

# Sample data
X = np.array([[1, 2],
              [2, 3],
              [3, 4],
              [4, 5],
              [5, 6]], dtype=float)

# Initialize scaler
scaler = MinMaxScaler()

# Fit and transform the data
X_scaled = scaler.fit_transform(X)

print("Original:\n", X)
print("Scaled:\n", X_scaled)


Original:
 [[1. 2.]
 [2. 3.]
 [3. 4.]
 [4. 5.]
 [5. 6.]]
Scaled:
 [[0.   0.  ]
 [0.25 0.25]
 [0.5  0.5 ]
 [0.75 0.75]
 [1.   1.  ]]


#### LabelEncoder

In [3]:
from sklearn.preprocessing import LabelEncoder

labels = ['Male', 'Female', 'Female', 'Male']
le = LabelEncoder()
encoded_labels = le.fit_transform(labels)

print(encoded_labels)  # Output: [1 0 0 1]

[1 0 0 1]


#### OneHotEncoder (One-Hot Encoding)

In [7]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

data = {'Employee id': [10, 20, 15, 25, 30],
        'Gender': ['M', 'F', 'F', 'M', 'F'],
        'Remarks': ['Good', 'Nice', 'Good', 'Great', 'Nice'],
        }
df = pd.DataFrame(data)
print(f"Employee data : \n{df}")

categorical_columns = df.select_dtypes(include=['object']).columns.tolist()
encoder = OneHotEncoder(sparse_output=False)

one_hot_encoded = encoder.fit_transform(df[categorical_columns])

one_hot_df = pd.DataFrame(one_hot_encoded, columns=encoder.get_feature_names_out(categorical_columns))

df_encoded = pd.concat([df, one_hot_df], axis=1)

df_encoded = df_encoded.drop(categorical_columns, axis=1)
print(f"Encoded Employee data : \n{df_encoded}")

Employee data : 
   Employee id Gender Remarks
0           10      M    Good
1           20      F    Nice
2           15      F    Good
3           25      M   Great
4           30      F    Nice
Encoded Employee data : 
   Employee id  Gender_F  Gender_M  Remarks_Good  Remarks_Great  Remarks_Nice
0           10       0.0       1.0           1.0            0.0           0.0
1           20       1.0       0.0           0.0            0.0           1.0
2           15       1.0       0.0           1.0            0.0           0.0
3           25       0.0       1.0           0.0            1.0           0.0
4           30       1.0       0.0           0.0            0.0           1.0


In [9]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

data = pd.DataFrame({'City': ['Delhi', 'Mumbai', 'Bangalore', 'Delhi']})
encoder = OneHotEncoder(sparse_output=False)
encoded_data = encoder.fit_transform(data[['City']])

print(encoded_data)


[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
