#### Array creation

In [2]:
import numpy as np
a1D = np.array([1, 2, 3, 4])
print('1D array:')
print(a1D)
a2D = np.array([[1, 2], [3, 4]])
print('2D array:')
print(a2D)
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print('3D array:')
print(a3D)


1D array:
[1 2 3 4]
2D array:
[[1 2]
 [3 4]]
3D array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### Creating arrays using arange

In [ ]:
# numpy.arange creates arrays with regularly incrementing values

import numpy as np
ar = np.arange(10)
print('1D array using arange:')
print(ar)
ar1 = np.arange(2, 10, dtype=int)
print('1D array with start, stop, and dtype:')
print(ar1)
ar3 = np.arange(2, 3, 0.1)
print('1D array with float step:')
print(ar3)

1D array using arange:
[0 1 2 3 4 5 6 7 8 9]
1D array with start, stop, and dtype:
[2 3 4 5 6 7 8 9]
1D array with float step:
[2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]


##### Common Array Initializations


In [8]:
ar1 = np.zeros((2, 3))        # 2x3 array of zeros
print(ar1)
ar2 = np.ones((3, 3))         # 3x3 array of ones
print(ar2)

ar3 = np.arange(0, 10, 2)  # 1D array with step of 2
print(ar3)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]


##### Array Attributes

In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)      # (2, 3)
print(arr.ndim)       # 2
print(arr.size)       # 6
print(arr.dtype)      # data type (e.g., int32)


(2, 3)
2
6
int64


#### Array Indexing & Slicing

In [14]:
# numpy indexing and slicing
a = np.array([10, 20, 30, 40, 50])
a[0]          # 10
a[1:4]        # [20, 30, 40]
a[-1]         # 50

np.int64(50)

####  Operations on Arrays

In [ ]:
# Element-wise operations:

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b  # addition
print(c) # Output: [5 7 9]
d = a * b  # multiplication
print(d) # Output: [4 10 18]

# Matrix multiplication:
sum = np.dot(a, b)  # Output: (1*4 + 2*5 + 3*6) = 32
print(sum)  

[5 7 9]
[ 4 10 18]
32


#### Aggregate functions:

In [19]:
a = np.array([1, 2, 3])
print(a.sum())
print(a.mean())
print(a.max())
print(a.min())


6
2.0
3
1


#### Reshaping

#### Reshaping

In [20]:
# reshape() :  changes the shape of an array without changing its data

a = np.arange(6)     # [0, 1, 2, 3, 4, 5]
b = a.reshape((2, 3))
print('Reshaped array:')
print(b)  # Output: [[0, 1, 2], [3, 4, 5]]

Reshaped array:
[[0 1 2]
 [3 4 5]]


#### Broadcasting

#### Scalar Broadcasting: A single value can be applied across an entire array.


In [22]:
import numpy as np
arr = np.array([1, 2, 3])
print(arr + 5)  # Output: [6 7 8]


a1 = np.array([2, 4, 6])
a2 = np.array([[1, 3, 5], [7, 9, 11]])
print(a1 + a2)

[6 7 8]
[[ 3  7 11]
 [ 9 13 17]]
